platform :ios, '8.0'
#use_frameworks!

target 'VoiceRecognition' do
    pod 'TSDemo_VoiceRecognition',      :path => '../’

    
    pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
end

target 'VoiceRecognitionTests' do
    
end
